AllCops:
  Include:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "*.gemspec"
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - Dangerfile
    - lib/interactor-contracts.rb
