cache: bundler
language: ruby
rvm:
  - 2.4
  - 2.5
  - jruby-head
  - ruby-head
script: bundle exec rspec
sudo: false

before_install:
  - gem update --system --no-doc
  - gem install bundler

bundler_args: --without development

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 2.6
      before_script:
        - bundle exec danger
      after_script:
        - bundle exec codeclimate-test-reporter
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS=''

addons:
  code_climate:
    repo_token: 4c8d32857f6271a921d0db0bdf9a316c47b5cc89827c85da862ab2738842dbb1
